// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlabdshafchgigpzybhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYWJkc2hhZmNoZ2lncHp5YmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDM1OTYsImV4cCI6MjA3MDYxOTU5Nn0.cqJDV7vCiUkJeobMbheRZNKs4YcnbN9F5OUN6hUbMFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});